spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/devicemanagement
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
server:
  port: 8090

